AllCops:
  TargetRubyVersion: 3.4
  UseCache: false
  SuggestExtensions: false
  DisabledByDefault: true
  Exclude:
    - bin/**
    - '**/vendor/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: true
  Max: 25

Metrics/AbcSize:
  Enabled: true
  Max: 30
