AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  UseCache: false
  Exclude:
    - bin/*
    - vendor/**/*
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30
